# Generated by Django 3.2.10 on 2021-12-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
    ]
